-- Ready Move Damage Type Mappings
-- This file maps ready moves to their damage types

local ready_moves = {
    ['??? Needles'] = { damage_type = 'piercing', charge_cost = "3" },
    ['Acid Mist'] = { damage_type = 'water', charge_cost = "1" },
    ['Acid Spray'] = { damage_type = 'water', charge_cost = "1" },
    ['Aqua Breath'] = { damage_type = 'water', charge_cost = "3" },
    ['Back Heel'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Beak Lunge'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Big Scissors'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Blockhead'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Blaster'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Brain Crush'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Bubble Shower'] = { damage_type = 'water', charge_cost = "1" },
    ['Bubble Curtain'] = { damage_type = 'buff', charge_cost = "3" },
    ['Chaotic Eye'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Charged Whisker'] = { damage_type = 'lightning', charge_cost = "2" },
    ['Choke Breath'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Chomp Rush'] = { damage_type = 'slashing', charge_cost = "3" },
    ['Claw Cyclone'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Corrosive Ooze'] = { damage_type = 'water', charge_cost = "3" },
    ['Crossthrash'] = { damage_type = 'slashing', charge_cost = "2" },
    ['Cursed Sphere'] = { damage_type = 'magic', charge_cost = "1" },
    ['Cyclotail'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Dark Spore'] = { damage_type = 'dark', charge_cost = "3" },
    ['Digest'] = { damage_type = 'magic', charge_cost = "1" },
    ['Disembowel'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Double Claw'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Drainkiss'] = { damage_type = 'dark', charge_cost = "1" },
    ['Dream Flower'] = { damage_type = 'dark', charge_cost = "2" },
    ['Dust Cloud'] = { damage_type = 'earth', charge_cost = "1" },
    ['Extirpating Salvo'] = { damage_type = 'blunt', charge_cost = "2" },
    ['Fantod'] = { damage_type = 'buff', charge_cost = "2" },
    ['Filamented Hold'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Fireball'] = { damage_type = 'fire', charge_cost = "1" },
    ['Fluid Spread'] = { damage_type = 'blunt', charge_cost = "2" },
    ['Fluid Toss'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Foot Kick'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Foul Waters'] = { damage_type = 'water', charge_cost = "2" },
    ['Frenzied Rage'] = { damage_type = 'buff', charge_cost = "1" },
    ['Frogkick'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Geist Wall'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Gloom Spray'] = { damage_type = 'dark', charge_cost = "2" },
    ['Gloeosuccus'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Grapple'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Harden Shell'] = { damage_type = 'buff', charge_cost = "1" },
    ['Head Butt'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Hi-Freq Field'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Hoof Volley'] = { damage_type = 'blunt', charge_cost = "3" },
    ['Infected Leech'] = { damage_type = 'magic', charge_cost = "1" },
    ['Infrasonics'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Intimidate'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Jettatura'] = { damage_type = 'debuff', charge_cost = "3" },
    ['Queasyshroom'] = { damage_type = 'dark', charge_cost = "2" },
    ['Lamb Chop'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Leaf Dagger'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Mandibular Bite'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Mega Scissors'] = { damage_type = 'slashing', charge_cost = "2" },
    ['Metallic Body'] = { damage_type = 'buff', charge_cost = "1" },
    ['Molting Plumage'] = { damage_type = 'wind', charge_cost = "1" },
    ['Nectarous Deluge'] = { damage_type = 'water', charge_cost = "2" },
    ['Needle Shot'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Nepenthic Plunge'] = { damage_type = 'water', charge_cost = "3" },
    ['Nihility Song'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Nimble Snap'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Noisome Powder'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Numbing Noise'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Numbshroom'] = { damage_type = 'dark', charge_cost = "2" },
    ['Palsy Pollen'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Pecking Flurry'] = { damage_type = 'piercing', charge_cost = "1" },
    ['Pentapeck'] = { damage_type = 'piercing', charge_cost = "3" },
    ['Pestilent Plume'] = { damage_type = 'dark', charge_cost = "2" },
    ['Power Attack'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Predatory Glare'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Purulent Ooze'] = { damage_type = 'water', charge_cost = "2" },
    ['Queasyshroom'] = { damage_type = 'dark', charge_cost = "1" },
    ['Rage'] = { damage_type = 'buff', charge_cost = "2" },
    ['Razor Fang'] = { damage_type = 'piercing', charge_cost = "1" },
    ['Recoil Dive'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Rhino Attack'] = { damage_type = 'piercing', charge_cost = "1" },
    ['Rhino Guard'] = { damage_type = 'buff', charge_cost = "1" },
    ['Rhino Wrecker'] = { damage_type = 'piercing', charge_cost = "2" },
    ['Rhinowrecker'] = { damage_type = 'piercing', charge_cost = "2" },
    ['Ripper Fang'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Roar'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Sandblast'] = { damage_type = 'magic', charge_cost = "2" },
    ['Sandpit'] = { damage_type = 'magic', charge_cost = "1" },
    ['Scissor Guard'] = { damage_type = 'buff', charge_cost = "2" },
    ['Scream'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Scythe Tail'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Secretion'] = { damage_type = 'buff', charge_cost = "1" },
    ['Sensilla Blades'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Shakeshroom'] = { damage_type = 'dark', charge_cost = "2" },
    ['Sheep Charge'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Sheep Song'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Sickle Slash'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Silence Gas'] = { damage_type = 'dark', charge_cost = "3" },
    ['Somersault'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Soporific'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Spider Web'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Spinning Top'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Spiral Spin'] = { damage_type = 'slashing', charge_cost = "1" },
    ['Spore'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Spoil'] = { damage_type = 'debuff', charge_cost = "1" },
    ['Stink Bomb'] = { damage_type = 'earth', charge_cost = "2" },
    ['Suction'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Sudden Lunge'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Sweeping Gouge'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Swooping Frenzy'] = { damage_type = 'piercing', charge_cost = "2" },
    ['Tail Blow'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Tegmina Buffet'] = { damage_type = 'slashing', charge_cost = "2" },
    ['Tickling Tendrils'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Tortoise Stomp'] = { damage_type = 'blunt', charge_cost = "1" },
    ['Toxic Spit'] = { damage_type = 'debuff', charge_cost = "2" },
    ['TP Drainkiss'] = { damage_type = 'dark', charge_cost = "3" },
    ['Venom'] = { damage_type = 'water', charge_cost = "1" },
    ['Venom Shower'] = { damage_type = 'water', charge_cost = "2" },
    ['Venom Spray'] = { damage_type = 'debuff', charge_cost = "2" },
    ['Water Wall'] = { damage_type = 'buff', charge_cost = "3" },
    ['Whirl Claws'] = { damage_type = 'piercing', charge_cost = "1" },
    ['Wild Carrot'] = { damage_type = 'buff', charge_cost = "2" },
    ['Wild Oats'] = { damage_type = 'piercing', charge_cost = "1" },
    ['Wing Slap'] = { damage_type = 'blunt', charge_cost = "2" },
    ['Zealous Snort'] = { damage_type = 'buff', charge_cost = "3" },
}

function get_ready_move_type(move_name)
    return ready_moves[move_name] and ready_moves[move_name].damage_type or 'magic'
end

function get_ready_move_cost(move_name)
    return ready_moves[move_name] and ready_moves[move_name].charge_cost or "unknown"
end

return {
    get_ready_move_type = get_ready_move_type,
    get_ready_move_cost = get_ready_move_cost
}