--[[
* XIUI baked-in user config defaults (curated: only config-settable tuning).
* Deep-merged over the base defaults by core/settings/init.lua so a fresh
* install comes up in the intended look. Window PLACEMENT is excluded; users
* still drag windows themselves. Dead keys and float-noise are NOT included.
]]--

local M = {};

function M.createConfigOverrides()
    return T{
        ["StartKey"] = 1,
        ["alwaysShowMpBar"] = true,
        ["bovineLootyShowBoxes"] = true,
        ["bsthudImageSize"] = 70,
        ["bsthudShowBars"] = true,
        ["bsthudShowIcons"] = true,
        ["bsthudShowImage"] = true,
        ["bsthudShowMoves"] = true,
        ["castBarFastCast"] = T{
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 0,
            [5] = 0.4,
            [6] = 0,
            [7] = 0,
            [8] = 0,
            [9] = 0,
            [10] = 0,
            [11] = 0,
            [12] = 0,
            [13] = 0,
            [14] = 0,
            [15] = 0,
            [16] = 0,
            [17] = 0,
            [18] = 0,
            [19] = 0,
            [20] = 0,
            [21] = 0,
            [22] = 0,
        },
        ["castBarFastCastBRDSingSpeed"] = 0.25,
        ["castBarFastCastEnabled"] = true,
        ["castBarFastCastRDMSJ"] = 0.15,
        ["castBarFastCastWHMCureSpeed"] = 0.15,
        ["castCost"] = T{
            ["backgroundTheme"] = "Plain",
            ["showRecast"] = true,
        },
        ["castCostModern"] = false,
        ["colorCustomization"] = T{
            ["gilTracker"] = T{
                ["negativeColor"] = 4294919236,
                ["positiveColor"] = 4278255360,
                ["textColor"] = 4294967295,
            },
            ["inventoryTracker"] = T{
                ["emptySlotColor"] = T{
                    ["a"] = 1,
                    ["b"] = 0.17,
                    ["g"] = 0.07,
                    ["r"] = 0,
                },
                ["textColor"] = 4294967295,
                ["usedSlotColor"] = T{
                    ["a"] = 1,
                    ["b"] = 0.88,
                    ["g"] = 0.7,
                    ["r"] = 0.37,
                },
                ["usedSlotColorThreshold1"] = T{
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["usedSlotColorThreshold2"] = T{
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 1,
                },
            },
            ["partyListA"] = T{
                ["hpTextColor"] = -16777216,
                ["tpEmptyTextColor"] = -16777216,
            },
            ["partyListB"] = T{
                ["hpTextColor"] = -16777216,
                ["tpEmptyTextColor"] = -16777216,
            },
            ["partyListC"] = T{
                ["hpTextColor"] = -16777216,
                ["tpEmptyTextColor"] = -16777216,
            },
        },
        ["enableEnemyListClickTarget"] = true,
        ["enablePartyListClickTarget"] = true,
        ["enemyListDebuffsAnchor"] = "left",
        ["enemyListSortOrder"] = "asc",
        ["expBarInlineMode"] = false,
        ["expBarLimitPointsMode"] = true,
        ["expBarShowBookends"] = true,
        ["expBarShowPercent"] = true,
        ["expBarShowText"] = true,
        ["fontFamily"] = "Tahoma",
        ["fontOutlineWidth"] = 2,
        ["fontWeight"] = "Bold",
        ["gilTrackerIconRight"] = false,
        ["gilTrackerShowGilPerHour"] = false,
        ["healthBarFlashEnabled"] = true,
        ["hideDuringEvents"] = true,
        ["hideStockUI"] = T{
            ["castinfo"] = true,
            ["enabled"] = true,
            ["party0"] = true,
            ["party1"] = true,
            ["party2"] = true,
            ["target"] = false,
        },
        ["inventoryShowDots"] = false,
        ["inventoryShowLabels"] = true,
        ["inventoryTextUseThresholdColor"] = true,
        ["inventoryTrackerColorThreshold1"] = 41,
        ["inventoryTrackerColorThreshold2"] = 50,
        ["jobIconTheme"] = "FFXI",
        ["layoutCompact"] = T{
            ["barHeight"] = 20,
            ["barSpacing"] = 8,
            ["hpBarWidth"] = 200,
            ["hpTextOffsetX"] = -8,
            ["hpTextOffsetY"] = -1,
            ["mpBarWidth"] = 120,
            ["mpTextOffsetX"] = -4,
            ["mpTextOffsetY"] = -1,
            ["nameTextOffsetX"] = 1,
            ["nameTextOffsetY"] = 0,
            ["tpBarWidth"] = 0,
            ["tpTextOffsetX"] = 0,
            ["tpTextOffsetY"] = 1,
        },
        ["layoutHorizontal"] = T{
            ["barHeight"] = 20,
            ["barSpacing"] = 8,
            ["hpBarWidth"] = 150,
            ["hpTextOffsetX"] = -2,
            ["hpTextOffsetY"] = -1,
            ["mpBarWidth"] = 100,
            ["mpTextOffsetX"] = -2,
            ["mpTextOffsetY"] = -1,
            ["nameTextOffsetX"] = 1,
            ["nameTextOffsetY"] = 0,
            ["tpBarWidth"] = 100,
            ["tpTextOffsetX"] = -2,
            ["tpTextOffsetY"] = -1,
        },
        ["mobInfoHideWhenEngaged"] = false,
        ["mobInfoShowDetection"] = true,
        ["mobInfoShowImmunities"] = false,
        ["mobInfoShowJob"] = true,
        ["mobInfoShowLevel"] = true,
        ["mobInfoShowLink"] = true,
        ["mobInfoShowNoData"] = false,
        ["mobInfoShowResistances"] = true,
        ["mobInfoShowWeaknesses"] = true,
        ["mobInfoSingleRow"] = true,
        ["mobInfoSnapToTargetBar"] = true,
        ["noBookendRounding"] = 4,
        ["notificationsHideDuringEvents"] = true,
        ["notificationsShowGil"] = false,
        ["notificationsShowItems"] = false,
        ["notificationsShowKeyItems"] = false,
        ["notificationsShowTreasure"] = false,
        ["partyA"] = T{
            ["alignBottom"] = true,
            ["backgroundName"] = "Plain",
            ["flashTP"] = true,
            ["hpBarScaleX"] = 0.85,
            ["hpDisplayMode"] = "both",
            ["layout"] = 1,
            ["mpDisplayMode"] = "both",
            ["showDistance"] = true,
        },
        ["partyAnchors"] = T{
            ["party2"] = T{
                ["edge"] = "above",
                ["offsetY"] = -10,
                ["parent"] = "castcost",
            },
            ["party3"] = T{
                ["edge"] = "above",
                ["offsetY"] = -10,
                ["parent"] = "party2",
            },
        },
        ["partyB"] = T{
            ["alignBottom"] = true,
            ["backgroundName"] = "Plain",
            ["entrySpacing"] = 0,
            ["flashTP"] = true,
            ["jobIconScale"] = 1,
            ["layout"] = 2,
            ["scaleX"] = 1,
            ["scaleY"] = 1,
            ["showDistance"] = true,
            ["showTP"] = true,
        },
        ["partyC"] = T{
            ["alignBottom"] = true,
            ["backgroundName"] = "Plain",
            ["entrySpacing"] = 0,
            ["flashTP"] = true,
            ["jobIconScale"] = 1,
            ["layout"] = 2,
            ["scaleX"] = 1,
            ["scaleY"] = 1,
            ["showDistance"] = true,
            ["showTP"] = true,
        },
        ["partyListAlliance"] = true,
        ["partyListAnchorCastCost"] = true,
        ["partyListHideDuringEvents"] = true,
        ["partyListLayout2"] = T{
            ["barHeight"] = 20,
            ["barSpacing"] = 8,
            ["hpBarScaleX"] = 0.9,
            ["hpBarScaleY"] = 1,
            ["hpBarWidth"] = 200,
            ["hpTextOffsetX"] = -8,
            ["hpTextOffsetY"] = -1,
            ["mpBarScaleX"] = 0.6,
            ["mpBarScaleY"] = 0.7,
            ["mpBarWidth"] = 120,
            ["mpTextOffsetX"] = -4,
            ["mpTextOffsetY"] = -1,
            ["nameTextOffsetX"] = 1,
            ["nameTextOffsetY"] = 0,
            ["partyList2DistanceFontSize"] = 12,
            ["partyList2EntrySpacing"] = 1,
            ["partyList2FontSize"] = 12,
            ["partyList2HpBarScaleX"] = 0.9,
            ["partyList2HpBarScaleY"] = 1,
            ["partyList2HpFontSize"] = 12,
            ["partyList2JobFontSize"] = 12,
            ["partyList2JobIconScale"] = 0.65,
            ["partyList2MpBarScaleX"] = 0.6,
            ["partyList2MpBarScaleY"] = 0.7,
            ["partyList2MpFontSize"] = 12,
            ["partyList2NameFontSize"] = 12,
            ["partyList2ScaleX"] = 0.55,
            ["partyList2ScaleY"] = 0.55,
            ["partyList2TP"] = true,
            ["partyList2TpFontSize"] = 12,
            ["partyList3DistanceFontSize"] = 12,
            ["partyList3EntrySpacing"] = 1,
            ["partyList3FontSize"] = 12,
            ["partyList3HpBarScaleX"] = 0.9,
            ["partyList3HpBarScaleY"] = 1,
            ["partyList3HpFontSize"] = 12,
            ["partyList3JobFontSize"] = 12,
            ["partyList3JobIconScale"] = 0.65,
            ["partyList3MpBarScaleX"] = 0.6,
            ["partyList3MpBarScaleY"] = 0.7,
            ["partyList3MpFontSize"] = 12,
            ["partyList3NameFontSize"] = 12,
            ["partyList3ScaleX"] = 0.55,
            ["partyList3ScaleY"] = 0.55,
            ["partyList3TP"] = true,
            ["partyList3TpFontSize"] = 12,
            ["partyListDistanceFontSize"] = 12,
            ["partyListEntrySpacing"] = 3,
            ["partyListFontSize"] = 12,
            ["partyListHpFontSize"] = 12,
            ["partyListJobFontSize"] = 12,
            ["partyListJobIconScale"] = 1,
            ["partyListMinRows"] = 1,
            ["partyListMpFontSize"] = 12,
            ["partyListNameFontSize"] = 12,
            ["partyListScaleX"] = 1,
            ["partyListScaleY"] = 1,
            ["partyListTP"] = true,
            ["partyListTpFontSize"] = 12,
            ["selectionBoxOffsetY"] = 0,
            ["selectionBoxScaleY"] = 1,
            ["splitFontSizes"] = true,
            ["tpBarWidth"] = 0,
            ["tpTextOffsetX"] = 0,
            ["tpTextOffsetY"] = 1,
        },
        ["partyListPreview"] = true,
        ["partyListShiftDrag"] = true,
        ["petBarAutomaton"] = T{
            ["showTimers"] = false,
        },
        ["petBarAvatar"] = T{
            ["backgroundTheme"] = "Plain",
            ["showLevel"] = true,
        },
        ["petBarAvatarSettings"] = T{
            ["diabolos"] = T{
                ["offsetX"] = -161,
            },
        },
        ["petBarBstShowCallBeast"] = true,
        ["petBarCharm"] = T{
            ["backgroundTheme"] = "Plain",
        },
        ["petBarDrgShowDeepBreathing"] = false,
        ["petBarJug"] = T{
            ["backgroundTheme"] = "Plain",
        },
        ["petBarPreviewType"] = 2,
        ["petBarReadyBaseRecast"] = 45,
        ["petBarWyvern"] = T{
            ["backgroundTheme"] = "Plain",
            ["imageOffsetX"] = -80,
            ["imageOffsetY"] = 0,
            ["imageOpacity"] = 0.41,
        },
        ["playerBarHpDisplayMode"] = "Number (Percent)",
        ["playerBarMpDisplayMode"] = "Number (Percent)",
        ["showCastBarBookends"] = false,
        ["showEnemyId"] = true,
        ["showEnemyListBookends"] = false,
        ["showPartyListBookends"] = false,
        ["showPartyListTarget"] = true,
        ["showPartyListWhenSolo"] = true,
        ["showPlayerBarBookends"] = true,
        ["showTargetBarBookends"] = true,
        ["tooltipScale"] = 1,
        ["treasurePoolPreview"] = true,
        ["treasurePoolShowTimerBar"] = false,
    };
end

return M;